---
title: "Modelo"
author: "Juan Escalona"
date: "5/25/2022"
output: html_document
---

```{r setup, include=FALSE}
#--- Usar espejo CRAN del ITAM ---
options(repos="http://cran.itam.mx/")

#--- Funciones utiles ---
prob<-function(x){
  out<-min(length(x[x>0])/length(x),length(x[x<0])/length(x))
  out
}
```

```{r}
library(ggplot2)
library(tidyverse)
library(R2jags)
library(dplyr)
```

Carga de datos

```{r}
australia <- read.csv(file = 'city_by_year_sin_0.csv', check.names = F)
```

```{r}
colnames(australia)
```

```{r}
names(australia)[1] <- 'year'
```

```{r}
australia_2011 <- australia[australia$year==2011,]
australia_2011<- australia_2011 %>% mutate(rain_days=RainTomorrow*days_in_year)
n<-nrow(australia_2011)
```


```{r}
plot(australia_2011$RainTomorrow)

```

```{r}
plot(australia_2011$Rainfall)
```

```{r}
data<-list("n"=n,"y"=australia_2011$rain_days,"ne"=australia_2011$days_in_year, "x1"=australia_2011$Rainfall, "x2"=australia_2011$WindSpeed3pm, "x3"=australia_2011$Humidity3pm, "x4"=australia_2011$Pressure3pm)
```

```{r}
inits<-function(){list(beta=rep(0,5), yf1=rep(1,n))}
parsbc<-c("beta","p")
```

```{r}
modelo_base.sim<-jags(data,inits,parsbc,model.file="modelo.txt",
               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1) 
```

```{r}
out<-modelo_base.sim$BUGSoutput$sims.list
```

```{r}
z<-out$p[,2]
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
```
```{r}
out.sum<-modelo_base.sim$BUGSoutput$summary
```

```{r}
out.sum.t<-out.sum[grep("p",rownames(out.sum)),c(1,3,7)]
out.sum.t<-cbind(out.sum.t,apply(out$p,2,prob))
dimnames(out.sum.t)[[2]][4]<-"prob"
print(out.sum.t)
```

```{r}
out.dic<-modelo_base.sim$BUGSoutput$DIC
print(out.dic)
```

```{r}
out.p<-out.sum[grep("p",rownames(out.sum)),]
```

```{r}
par(mfrow=c(1,1))
plot(australia_2011$rain_days/australia_2011$days_in_year,type="p",col="grey50", xlab="Ciudadades", ylab="Probabilidad de lluvia")
points(out.p[,1],col=2,pch=16,cex=0.5)
segments(1:46,out.p[,3],1:46,out.p[,7],col=2)
points(47,sum(australia_2011$rain_days)/sum(australia_2011$days_in_year), col="blue")
```


```{r}
out.sum.t<-out.sum[grep("beta",rownames(out.sum)),c(1,3,7)]
out.sum.t<-cbind(out.sum.t,apply(out$beta,2,prob))
dimnames(out.sum.t)[[2]][4]<-"prob"
print(out.sum.t)
```

# Modelo Probit

```{r}
modelo_probit.sim<-jags(data,inits,parsbc,model.file="modelo.txt",
               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1) 
```
```{r}
out_probit<-modelo_probit.sim$BUGSoutput$sims.list
```

```{r}
z<-out_probit$p[,2]
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
```
```{r}
out_probit.sum<-modelo_probit.sim$BUGSoutput$summary
```

```{r}
out_probit.sum.t<-out_probit.sum[grep("p",rownames(out_probit.sum)),c(1,3,7)]
out_probit.sum.t<-cbind(out_probit.sum.t,apply(out_probit$p,2,prob))
dimnames(out_probit.sum.t)[[2]][4]<-"prob"
print(out_probit.sum.t)
```

```{r}
out_probit.dic<-modelo_probit.sim$BUGSoutput$DIC
print(out_probit.dic)
```

```{r}
out_probit.p<-out_probit.sum[grep("p",rownames(out_probit.sum)),]
```

```{r}
par(mfrow=c(1,1))
plot(australia_2011$rain_days/australia_2011$days_in_year,type="p",col="grey50", xlab="Ciudadades", ylab="Probabilidad de lluvia")
points(out_probit.p[,1],col=2,pch=16,cex=0.5)
segments(1:46,out_probit.p[,3],1:46,out_probit.p[,7],col=2)
points(47,sum(australia_2011$rain_days)/sum(australia_2011$days_in_year), col="blue")
```

```{r}
out_probit.sum.t<-out_probit.sum[grep("beta",rownames(out_probit.sum)),c(1,3,7)]
out_probit.sum.t<-cbind(out_probit.sum.t,apply(out_probit$beta,2,prob))
dimnames(out_probit.sum.t)[[2]][4]<-"prob"
print(out_probit.sum.t)
```

# Modelo cloglog

```{r}
modelo_cloglog.sim<-jags(data,inits,parsbc,model.file="modelo.txt",
               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1) 
```
```{r}
out_cloglog<-modelo_cloglog.sim$BUGSoutput$sims.list
```

```{r}
z<-out_cloglog$p[,2]
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
```
```{r}
out_cloglog.sum<-modelo_cloglog.sim$BUGSoutput$summary
```

```{r}
out_cloglog.sum.t<-out_cloglog.sum[grep("p",rownames(out_cloglog.sum)),c(1,3,7)]
out_cloglog.sum.t<-cbind(out_cloglog.sum.t,apply(out_cloglog$p,2,prob))
dimnames(out_cloglog.sum.t)[[2]][4]<-"prob"
print(out_cloglog.sum.t)
```

```{r}
out_cloglog.dic<-modelo_cloglog.sim$BUGSoutput$DIC
print(out_cloglog.dic)
```

```{r}
out_cloglog.p<-out_cloglog.sum[grep("p",rownames(out_cloglog.sum)),]
```

```{r}
par(mfrow=c(1,1))
plot(australia_2011$rain_days/australia_2011$days_in_year,type="p",col="grey50", xlab="Ciudadades", ylab="Probabilidad de lluvia")
points(out_cloglog.p[,1],col=2,pch=16,cex=0.5)
segments(1:46,out_cloglog.p[,3],1:46,out_cloglog.p[,7],col=2)
points(47,sum(australia_2011$rain_days)/sum(australia_2011$days_in_year), col="blue")
```

```{r}
out_cloglog.sum.t<-out_cloglog.sum[grep("beta",rownames(out_cloglog.sum)),c(1,3,7)]
out_cloglog.sum.t<-cbind(out_cloglog.sum.t,apply(out_cloglog$beta,2,prob))
dimnames(out_cloglog.sum.t)[[2]][4]<-"prob"
print(out_cloglog.sum.t)
```

# Modelo loglog

```{r}
modelo_loglog.sim<-jags(data,inits,parsbc,model.file="modelo.txt",
               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1) 
```
```{r}
out_loglog<-modelo_loglog.sim$BUGSoutput$sims.list
```

```{r}
z<-out_loglog$p[,2]
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
```
```{r}
out_loglog.sum<-modelo_loglog.sim$BUGSoutput$summary
```

```{r}
out_loglog.sum.t<-out_loglog.sum[grep("p",rownames(out_loglog.sum)),c(1,3,7)]
out_loglog.sum.t<-cbind(out_loglog.sum.t,apply(out_loglog$p,2,prob))
dimnames(out_loglog.sum.t)[[2]][4]<-"prob"
print(out_loglog.sum.t)
```

```{r}
out_loglog.dic<-modelo_loglog.sim$BUGSoutput$DIC
print(out_loglog.dic)
```

```{r}
out_loglog.p<-out_loglog.sum[grep("p",rownames(out_loglog.sum)),]
```

```{r}
par(mfrow=c(1,1))
plot(australia_2011$rain_days/australia_2011$days_in_year,type="p",col="grey50", xlab="Ciudadades", ylab="Probabilidad de lluvia")
points(out_loglog.p[,1],col=2,pch=16,cex=0.5)
segments(1:46,out_loglog.p[,3],1:46,out_loglog.p[,7],col=2)
points(47,sum(australia_2011$rain_days)/sum(australia_2011$days_in_year), col="blue")
```

```{r}
out_loglog.sum.t<-out_loglog.sum[grep("beta",rownames(out_loglog.sum)),c(1,3,7)]
out_loglog.sum.t<-cbind(out_loglog.sum.t,apply(out_loglog$beta,2,prob))
dimnames(out_loglog.sum.t)[[2]][4]<-"prob"
print(out_loglog.sum.t)
```

# Modelo loglog sin pressure3pm

```{r}
data2<-list("n"=n,"y"=australia_2011$rain_days,"ne"=australia_2011$days_in_year, "x1"=australia_2011$Rainfall, "x2"=australia_2011$WindSpeed3pm, "x3"=australia_2011$Humidity3pm)
```

```{r}
inits2<-function(){list(beta=rep(0,4), yf1=rep(1,n))}
parsbc<-c("beta","p")
```

```{r}
modelo_loglog2.sim<-jags(data,inits2,parsbc,model.file="modelo.txt",
               n.iter=50000,n.chains=2,n.burnin=5000,n.thin=1) 
```
```{r}
out_loglog2<-modelo_loglog2.sim$BUGSoutput$sims.list
```

```{r}
z<-out_loglog2$p[,2]
par(mfrow=c(2,2))
plot(z,type="l")
plot(cumsum(z)/(1:length(z)),type="l")
hist(z,freq=FALSE)
acf(z)
```
```{r}
out_loglog2.sum<-modelo_loglog2.sim$BUGSoutput$summary
```

```{r}
out_loglog2.sum.t<-out_loglog2.sum[grep("p",rownames(out_loglog2.sum)),c(1,3,7)]
out_loglog2.sum.t<-cbind(out_loglog2.sum.t,apply(out_loglog2$p,2,prob))
dimnames(out_loglog2.sum.t)[[2]][4]<-"prob"
print(out_loglog2.sum.t)
```

```{r}
out_loglog2.dic<-modelo_loglog2.sim$BUGSoutput$DIC
print(out_loglog2.dic)
```

```{r}
out_loglog2.p<-out_loglog2.sum[grep("p",rownames(out_loglog2.sum)),]
```

```{r}
par(mfrow=c(1,1))
plot(australia_2011$rain_days/australia_2011$days_in_year,type="p",col="grey50", xlab="Ciudadades", ylab="Probabilidad de lluvia")
points(out_loglog2.p[,1],col=2,pch=16,cex=0.5)
segments(1:46,out_loglog2.p[,3],1:46,out_loglog2.p[,7],col=2)
points(47,sum(australia_2011$rain_days)/sum(australia_2011$days_in_year), col="blue")
```

```{r}
out_loglog2.sum.t<-out_loglog2.sum[grep("beta",rownames(out_loglog2.sum)),c(1,3,7)]
out_loglog2.sum.t<-cbind(out_loglog2.sum.t,apply(out_loglog2$beta,2,prob))
dimnames(out_loglog2.sum.t)[[2]][4]<-"prob"
print(out_loglog2.sum.t)
```